[package]
name = "lump"
version = "0.1.0"
edition = "2024"

[workspace]
members = [ 
	"bin_examples/clappy_by_lump", 
	"libs/lump_clap", 
	"libs/lump_core",
	"libs/lump_db",
	"libs/lump_db_derive",
	"libs/lump_derive",
	"libs/lump_params_client",
	"libs/lump_trigger"
]

[workspace.dependencies]
futures = { version = "0.3.31", default-features = false, features = ["std", "async-await"] }

[dependencies]
lump_core = { path = "libs/lump_core" }
serde = "1.0"
toml = "0.8"
futures = { workspace = true }
tokio = { version = ">=1.2", default-features = false, features = ["rt"] }
