[package]
name = "lump"
version = "0.1.0"
edition = "2024"

[workspace]
members = [ "bin_examples/clappy_by_lump", "libs/lump_clap", "libs/lump_core","libs/lump_db", "libs/lump_derive"]

[dependencies]
lump_core = { path = "libs/lump_core" }
serde = "1.0"
toml = "0.8"
